# Generated by Django 5.0.3 on 2024-04-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_task_user_task_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated',
        ),
    ]
